#!/usr/bin/env php

<?php

require_once __DIR__ . '/constants.php';

require_once BASE_PATH . '/vendor/autoload.php';

use Elementary\Kernel\ConsoleKernel;

$kernel = new ConsoleKernel();
$kernel->bootstrap();

$statusCode = $kernel->handleCli($argv);

$kernel->terminateCli($statusCode);
exit($statusCode);